Repository PrestaShop/classic-theme, pull requests merged in 2024-09, with the labels that each got.

#153 Remove meta keywords
  templates/_partials/head.tpl
Labels: Waiting for QA, Blocked

#154 Use new way to access category images
  templates/catalog/_partials/category-header.tpl
  templates/catalog/_partials/subcategories.tpl
Labels: QA ✔️

#155 Update for node iron lts
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .gitignore
  _dev/.stylelintignore
  _dev/.stylelintrc
  _dev/css/partials/_commons.scss
  _dev/css/partials/_fonts.scss
  _dev/css/partials/_variables.scss
  _dev/css/theme.scss
  _dev/package-lock.json
  _dev/package.json
  _dev/webpack.config.js
Labels: QA ✔️, dependencies, task
